name: "Update README with most recent blog post"
on: push
permissions:
  contents: write

jobs:
  recent_post_job:
    runs-on: ubuntu-latest
    name: Recent Post
    steps:
      - name: Checkout repo
        uses: "actions/checkout@v4"

      - name: Recent post action
        id: recent-post
        uses: "it176131/it176131.github.io/.github/actions/recent-posts@v1"

      - name: Commit README
        run: |
          echo $(git diff --name-only)
          git config user.email github-actions@github.com
          git config user.name github-actions
          git add .
          git commit -m "Synced and updated with most recent it176131.github.io blog post"
          git push