name: "Update README with most recent blog post"
on: push

jobs:
  recent_post_job:
    runs-on: ubuntu-latest
    name: Recent Post
    steps:
      - name: Checkout repo
        uses: "actions/checkout@v4"

      - name: Recent post action
        id: recent-post
        uses: "it176131/it176131.github.io/.github/actions/recent-posts@v1"

      - name: Get the result
        run: echo ${{ steps.recent-post.outputs.result }}